### ISSUE TITLE
kotlin1.4.20报错

### ISSUE THREAD

**Issue by TruthKeeper** [bytedance/ByteX#111]
AGP : 4.1.3
gradle version: 6.5
kotlin plugin version: 1.4.20
byteX verson: 0.3.0

gradle.properties中配置了如下，但是仍未解决
```
bytex.forbidUseLenientMutationDuringGetArtifact=true
bytex.enableDuplicateClassCheck=false
```

> Task :app:transformClassesWithByteXForDebug FAILED
Execution failed for task ':app:transformClassesWithByteXForDebug'.
> java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: null
  	Failed to resolve class META-INF/versions/9/module-info.class[
  transform input:
  	/Users/a123/.gradle/caches/transforms-2/files-2.1/4b49e80d82a9761aadbf69c6e609c197/jetified-kotlin-stdlib-1.4.20.jar!META-INF/versions/9/module-info.class
  project input:
  	/Users/a123/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.4.20/9be77b243a362b745e365f286627b8724337009c/kotlin-stdlib-1.4.20.jar!META-INF/versions/9/module-info.class
  aar input:not found]

**Comment by yangzhiqian** [comment]
app/build/ByteX/xxxx/bytex_log.txt发一下，里面有更多有用的报错堆栈

**Comment by TruthKeeper** [comment]
ok解决了，是自己代码不严谨抛出的空指针
