### ISSUE TITLE
shrinkR如何keep包名下所有R资源，试了com.xx.xx/com.xx.xx.R都不行，只能单个keep么，比如com.xx.xx.R.id/com.xx.xx.R.string这种

### ISSUE THREAD

**Issue by 5669146xing** [bytedance/ByteX#112]

**Comment by yangzhiqian** [comment]
R.string.kakao*这种

**Comment by yangzhiqian** [comment]
加上通配符再试试

**Comment by 5669146xing** [comment]
> 加上通配符再试试

因为打完包 安装运行直接是java.lang.NoClassDefFoundError: Failed resolution of: Lcom/xx/xx/x/R$string;
或java.lang.NoClassDefFoundError: Failed resolution of: Lcom/xx/xx/x/R$layout;这种，所以得整个包名下keep，这个得有什么办法么

**Comment by 5669146xing** [comment]
> 加上通配符再试试
com.xx.x.R/com.xx.x/com.xx.x.R.*这种我都试了下 不行好像

**Comment by yangzhiqian** [comment]
有可能你这个R或者对应的资源就没有，之前我们也遇到过，可能是你来的资源对应的库的版本不对导致的。你查查试试。

**Comment by yangzhiqian** [comment]
你报错的堆栈应该可以找到在索引哪个id时报错，看看对应id的资源是否存在。Android的R使用在library编译时就会调用，但对应的R字段生成是在app的appt时生成的。

**Comment by 5669146xing** [comment]
> 你报错的堆栈应该可以找到在索引哪个id时报错，看看对应id的资源是否存在。Android的R使用在library编译时就会调用，但对应的R字段生成是在app的appt时生成的。
看了下 好像是对应的资源不存在 这种情况要怎=怎么处理呢 就keep那一个吗

**Comment by yangzhiqian** [comment]
首先，这个问题不是bytex插件搞出来的，是因为你的app编译时就缺少资源导致aapt不生成对应的字段，所以需要补齐这个资源(大部分是因为依赖库版本不兼容导致的)，或者你看看你的依赖先(着重看一下报错类所在的lib和资源所在的lib这两个库的版本)。这个只能去修改库的版本。

**Comment by 5669146xing** [comment]
> 首先，这个问题不是bytex插件搞出来的，是因为你的app编译时就缺少资源导致aapt不生成对应的字段，所以需要补齐这个资源(大部分是因为依赖库版本不兼容导致的)，或者你看看你的依赖先(着重看一下报错类所在的lib和资源所在的lib这两个库的版本)。这个只能去修改库的版本。

额 不好意思 刚看错了。资源是有的

**Comment by yangzhiqian** [comment]
你可以看看app/build/intermediates下面(下图是高版本的)的jar中有没有报错的哪个R.class和字段。
![image](https://user-images.githubusercontent.com/17828748/132194674-b718ff21-f66f-4135-bb29-bcbe7f0e6346.png)
如果你没有上面哪个jar，可以看看app/build/generated/unnamespace_r_java(目录记不太起来了)下面有没有对应的R和字段

**Comment by 5669146xing** [comment]
> 你可以看看app/build/intermediates下面(下图是高版本的)的jar中有没有报错的哪个R.class和字段。
> ![image](https://user-images.githubusercontent.com/17828748/132194674-b718ff21-f66f-4135-bb29-bcbe7f0e6346.png)
> 如果你没有上面哪个jar，可以看看app/build/generated/unnamespace_r_java(目录记不太起来了)下面有没有对应的R和字段

在generated/not_namespaced_r_class_sources/debug/processDebugResources下找到了，有对应R和字段的。

**Comment by yangzhiqian** [comment]
1，确定一下包名和字段名完全符合，2可以看一下app/build/intermediates/transforms/bytex/的目录下应该有一个目录也可找到对应的输出的修改后的R,如果没有就是被优化掉了。3，问一下你这个报错点事反射调用的吗？还是正常的使用R.xx.xxx。

**Comment by 5669146xing** [comment]
> 1，确定一下包名和字段名完全符合，2可以看一下app/build/intermediates/transforms/bytex/的目录下应该有一个目录也可找到对应的输出的修改后的R,如果没有就是被优化掉了。3，问一下你这个报错点事反射调用的吗？还是正常的使用R.xx.xxx。

build/transforms/ShirkRFile下是有的，R.class以及对应资源id也是有的，就正常调用。不知道是不是我们远程构建平台构建apk的时候做了一些其他操作，我就想着整个包名先keep了，算了 ，我再看下吧。麻烦您了，🙏

**Comment by lkang08** [comment]
> 

请问下这个问题最后怎么处理了？我也遇到一样的问题
