### ISSUE TITLE
 编译不通过  duplicate entry: META-INF/maven/com.belerweb/pinyin4j/pom.properties

### ISSUE THREAD

**Issue by huopochuan** [bytedance/ByteX#113]
> java.lang.RuntimeException: java.lang.RuntimeException: java.util.zip.ZipException: duplicate entry: META-INF/maven/com.belerweb/pinyin4j/pom.properties

**Comment by huopochuan** [comment]
https://johnsonlee.io/2019/12/29/booster-v0-28-0-released/
![image](https://user-images.githubusercontent.com/7405212/132506340-0043bc16-e199-463c-8afe-66761b3ce033.png)

应该和这有关

**Comment by yangzhiqian** [comment]
如果没有搞错的话，如果你在mac的机器上用unzip解压你那个jar也会有报错提示，是否覆盖，这个应该是使用了windows打包出的jar，windows是区分大小写的，但mac是不区分的。bytex也是用jre的库读取和写入jar的，对于大小写问题,框架层也不好直接处理，这个业务方处理是更合理些吧

**Comment by huopochuan** [comment]
用的mac电脑构建的，把pinyin4j这个库从2.5.0升级到2.5.1就好了

**Comment by yangzhiqian** [comment]
嗯，修复了就好，其他遇到类似问题的伙伴请同样检查一下，entry重复。
