### ISSUE TITLE
enableDuplicateClassCheck配置不生效

### ISSUE THREAD

**Issue by MichaelJokAr** [bytedance/ByteX#115]
`gradle.properties` 里加上了`bytex.enableDuplicateClassCheck=false`；但是编译bytx_log里还是提示
`ERROR [byteX     ] We found duplicate module-info class files in the project.`
![image](https://user-images.githubusercontent.com/8246218/133380826-78511de8-88b2-461c-bc6f-8d0d7a1acb65.png)

![image](https://user-images.githubusercontent.com/8246218/133380937-66c79058-e722-43cf-a087-3be223449a76.png)

**Comment by yangzhiqian** [comment]
这个没有中断你的编译吧？我们在抑制了异常也会将信息打印到日志中。

**Comment by yangzhiqian** [comment]
你上面截图的日志看，插件是正常运行结束的。

**Comment by MichaelJokAr** [comment]
是的没有中断编译，所以这个error不用关注对吧

**Comment by yangzhiqian** [comment]
特意处理的

**Comment by yangzhiqian** [comment]
invalid
