### ISSUE TITLE
bytex.quick_refer_check能替代bytex.refer_check的功能么，集成过程中发现transformClassesWithRefer_check任务会卡住(跑了10多个小时还未结束)，可能是我的项目结构有问题

### ISSUE THREAD

**Issue by githubliangzai** [bytedance/ByteX#127]

**Comment by TellH** [comment]
可以改一下插件代码加一下日志排查~ 一般超过5分钟就不太符合预期了

**Comment by TellH** [comment]
bytex.quick_refer_check这个插件跟bytex.refer_check代码和功能差不多，但bytex.quick_refer_check不依赖transform，使用场景是合码前做一个快速检查，大概十几秒。bytex.refer_check一般是代码合入主干后打包时做。

**Comment by githubliangzai** [comment]
@TellH 感谢回答，找到任务卡住的原因了，是因为有循环依赖

**Comment by BaeBae33** [comment]
> @TellH 感谢回答，找到任务卡住的原因了，是因为有循环依赖

@githubliangzai  请问在哪加日志能找到？
