### ISSUE TITLE
R too large problem

### ISSUE THREAD

**Issue by bytebeats** [bytedance/ByteX#130]
I only saw Context#shouldDiscardRClasses(which size is 1000) to collect R[#group].xxx information and then inline their values in JarInput/DirectoryInput.

But what if R too large to cause Context#shouldDiscardRClasses OOM?

What's the solution to this problem? Is it in this package?

Thanks in advance.

**Comment by TellH** [comment]
shouldDiscardRClasses initial size is 1000, it can expand capacity automatically, so don't worry.
So as to OOM problem, it's hard to imagine how it would  happen, unless your project is very very large...
