### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by shenglintang** [bytedance/ByteX#14]
Execution failed for task ':app:transformClassesWithByteXFor。。。'.
> can not create log file

**Comment by yangzhiqian** [comment]
麻烦提供一下编译报错堆栈，可以加上--stacktrace

**Comment by yangzhiqian** [comment]
还在吗？上面的信息只能看到失败了，但没有日志无法分析，或者可以提供更多的环境信息。不回复的3天后关闭issue。

**Comment by yangzhiqian** [comment]
no reply,close!
