### ISSUE TITLE
常量优化的时候，编译期常量除了注解等方式显示表明，会被优化掉？然后反射会找不到这个字段？

### ISSUE THREAD

**Issue by TmacZhang** [bytedance/ByteX#16]
INFO [delete const field] delete airconditioner/com/myapplication/Const static final Ljava/lang/String; CONST_C = 1sss3
INFO [delete const field] delete airconditioner/com/myapplication/Const static final Ljava/lang/String; CONST_A = 1233

package airconditioner.com.myapplication;

public class Const {
    public static final String CONST_C = "1sss3";
    public static final String CONST_A = "1233";
    public static final String CONST_B = Const.class.getSimpleName();
}

Class clazz = Class.forName("airconditioner.com.myapplication.Const");
Object obj = clazz.newInstance();
Field field = clazz.getField("CONST_A");
Log.i(TAG, "onCreate CONST_A = " + field.get(obj));
Field field2 = clazz.getField("CONST_B");
Log.i(TAG, "onCreate CONST_B = " + field2.get(obj));

 onCreate exception
 	java.lang.NoSuchFieldException: CONST_A
  	at java.lang.Class.getField(Class.java:1601)
  	at airconditioner.com.myapplication.MainActivity.onCreate(MainActivity.java:79)
  	at android.app.Activity.performCreate(Activity.java:7136)
  	at android.app.Activity.performCreate(Activity.java:7127)

**Comment by yangzhiqian** [comment]
是的，这个文档中有说明，需要自己白名单(抖音也手动加，配合后面说到能分析到的就自动跳过优化。这样的情况很少，所以没有解析keep规则)，插件支持autoFilterReflectionField(特定的api分析反射), supposesReflectionWithString(所有字符串都作为可能的反射字段分析)两种类型的静态分析扫描，反射情况通过静态扫描无法百分百准确.
