### ISSUE TITLE
更改资源文件后，build失败

### ISSUE THREAD

**Issue by HiJohn** [bytedance/ByteX#17]
app\build\ByteX\shrinkR\shrinkR_log.txt: 另一个程序正在使用此文件，进程无法访问。

**Comment by yangzhiqian** [comment]
感谢反馈。这个看像文件占用的问题，请问一下当时是不是有用其他软件打开这个txt文件呢？

**Comment by HiJohn** [comment]
除了Android Studio应该没有其他打开这个文件的，
我主用win10有这个问题，别人用mac和ubuntu还没出现

**Comment by yangzhiqian** [comment]
本周会提一个更新上来，只能尽量保证bytex这边结束处理后正常释放掉这个文件。目前内部使用ByteX还没有这类反馈。

**Comment by yangzhiqian** [comment]
> 除了Android Studio应该没有其他打开这个文件的，
> 我主用win10有这个问题，别人用mac和ubuntu还没出现

已经提交了代码，后面可以使用新代码试试

**Comment by HiJohn** [comment]
使用新的版本不出现这个问题了
