### ISSUE TITLE
想知道会影响到加固或者热更新吗？

### ISSUE THREAD

**Issue by Neacy** [bytedance/ByteX#18]
如题，不知道对加固有影响吗？

热更新指tinker，tinker中的dex差量会有影响吗？

谢谢。

**Comment by yangzhiqian** [comment]
国内抖音有热修，一年多来都没有反馈过相关问题。tinker没有试过，不敢保证安全，但对于热更热修这类技术处理基本上都是在编译期间的后期，bytex在这些插件前处理,可以理解和proguard类似(但bytex更适合大家做技术扩展)，处理字节码，只要优化后的字节码符合规范，按照理论上讲，不会有影响。欢迎各位尝试并反馈问题，我们这边也会努力做好兼容。
