### ISSUE TITLE
关于ByteX的架构解析

### ISSUE THREAD

**Issue by GvcZhang** [bytedance/ByteX#20]
这两天在看 ByteX 的源码，目前进展不大，想问几个问题

1.  ByteX 的架构是怎样的？
2. 是一个怎样的流程把各个 plugin 组合在一起的？
3. 各个 plugin 又怎样去单独使用的?
4. 如何自己根据 ByteX 去写插件？

**Comment by yangzhiqian** [comment]
我按下面这种描述不知道能不能让你明白:
    1:ByteX是一个字节码框架平台，核心可以理解为common那个module,所有transform的输入输出都是这里做了，加上一些处理流程，还有一些基础功能(graph、log、locator)等提提供给插件使用。
    2、3： plugin都是通过注册使用的，如果当前的环境中`apply plugin: 'bytex'`这个插件(代码对应在base-plugin中)，后续apply的bytex插件(比如getter-setter，只要没有声明过alone模式)都会注册进bytex中，而不是注册进入到android plugin,然后执行bytex这个插件时，将所有注册的bytex插件同时处理了。同理，如果没有`apply plugin: 'bytex'`，这apply基于bytex的插件全部注册进入android plugin作为标准的transform执行。这个建议看AbsPlugin的代码.
    4:关于怎么写插件，建议你多看看我们的开发指引文档-https://github.com/bytedance/ByteX/blob/master/wiki/ByteX-Developer-API-zh.md

**Comment by GvcZhang** [comment]
`PluginConfig`模块仅仅是给每个 Plugin 生成 META-INF 信息吗

**Comment by GvcZhang** [comment]
感谢，你们的开发文档很有帮助。会持续关注

**Comment by GvcZhang** [comment]
你们的代码注释太少了，阅读起来有点费劲

**Comment by TellH** [comment]
@GvcZhang Hi，感谢关注。未来会有专门的文章聊聊ByteX的架构逻辑，另外如果还有疑问欢迎加微信群一起交流~

**Comment by GvcZhang** [comment]
感谢
