### ISSUE TITLE
关于 Extension 的处理 plugins 的逻辑

### ISSUE THREAD

**Issue by GvcZhang** [bytedance/ByteX#21]
观察`AbsPlugin`中的代码
```java
public final void apply(Project project) {
        this.project = project;
        this.android = project.getExtensions().getByType(AppExtension.class);
        ProjectOptions.INSTANCE.init(project);
        GlobalWhiteListManager.INSTANCE.init(project);
        Class<E> extensionClass = getExtensionClass();
        if (extensionClass != null) {
            Instantiator instantiator = ((DefaultGradle) project.getGradle()).getServices().get(Instantiator.class);
            extension = createExtension(instantiator, extensionClass);
            project.getExtensions().add(extension.getName(), extension);
        }
        onApply(project);
        String hookTransformName = hookTransformName();
        if (hookTransformName != null) {
            TransformHook.inject(project, android, this);
        } else {
            if (!alone()) {
                try {
                    ByteXExtension byteX = project.getExtensions().getByType(ByteXExtension.class);
                    byteX.registerPlugin(this);
                } catch (UnknownDomainObjectException e) {
                    android.registerTransform(getTransform());
                }
            } else {
                android.registerTransform(getTransform());
            }
        }
    }
```
比如我同时引入了 `SourceFileKiller` & `method-call-opt-plugin`两个插件，当编译 **example** 项目的时候其实都会走到`apply`方法，不过这里的`project`是单例的，是同一个代表**example**。然后反射可以拿到当前的插件 extension（例如当运行 SourceFileKiller 的时候，这里的 extension 就是**SourceFIleExtension**，它是通过 Instantiator 创建的），因为`project`是一个单例，所以可以通过`project.getExtensions().add(extension.getName(), extension);`这种方式添加到列表里。同时再后面判断是否 alone，再选择当前插件是否通过`android.registerTransform` 方法注册到 android 的 transform 里面。如果是`alone==false`然后通过 chain 来进行后续的处理。
`ByteX`就是通过这种方式来决定是单独处理还是集中处理的。

这种理解有没有问题？

**Comment by yangzhiqian** [comment]
ByteXExtension byteX = project.getExtensions().getByType(ByteXExtension.class);
byteX.registerPlugin(this);
上面这个才是决定是否集中处理还是单独处理。
如果你apply plugin "bytex",那project.getExtensions().getByType(ByteXExtension.class)会返回一个ByteXExtension,如果没有apply plugin "bytex",则会抛出异常，走下面的android.registerTransform(getTransform())；
project.getExtensions().add(extension.getName(), extension);这一行代码是为了注册插件对应的配置到gradle。

**Comment by GvcZhang** [comment]
这里是按照引入顺序来的吧，例如 method-call-opt-plugin 插件比 bytex 更早的引入，那么 method-call-opt-plugin 必然会走 android.registerTransform(getTransform())； 了？

**Comment by TellH** [comment]
> 这里是按照引入顺序来的吧，例如 method-call-opt-plugin 插件比 bytex 更早的引入，那么 method-call-opt-plugin 必然会走 android.registerTransform(getTransform())； 了？
> 就是说 bytex 只能做后面引入的插件的容器？

是的，如果插件apply到bytex之前，那么这个插件就是独立于bytex宿主的；反之，就会被bytex俘获，集成成一个整体运行

**Comment by GvcZhang** [comment]
> > 这里是按照引入顺序来的吧，例如 method-call-opt-plugin 插件比 bytex 更早的引入，那么 method-call-opt-plugin 必然会走 android.registerTransform(getTransform())； 了？
> > 就是说 bytex 只能做后面引入的插件的容器？
> 
> 是的，如果插件apply到bytex之前，那么这个插件就是独立于bytex宿主的；反之，就会被bytex俘获，集成成一个整体运行

好的，非常感谢。
