### ISSUE TITLE
你好 android 3.6.1报错

### ISSUE THREAD

**Issue by stytooldex** [bytedance/ByteX#24]
Cause: com/android/build/gradle/internal/transforms/ProGuardTransform
![image](https://user-images.githubusercontent.com/20622721/77698483-a4bbf300-6feb-11ea-84e8-391aef6f7f1e.png)

**Comment by yangzhiqian** [comment]
能用--stracktace 跑一下吗？这个日志有点少。是AGP3.6的版本吗？近期会有一个getter-setter中使用proguard configuration的bug fix,不知道是不是你遇到的这个问题。

**Comment by ymangu163** [comment]
我的也是gradle 3.6.1
![image](https://user-images.githubusercontent.com/9247244/78888493-4df6f480-7a94-11ea-9f36-5c4fca978dfa.png)

**Comment by johnsonlee** [comment]
> 我的也是gradle 3.6.1
> ![image](https://user-images.githubusercontent.com/9247244/78888493-4df6f480-7a94-11ea-9f36-5c4fca978dfa.png)

在 AGP `3.6.0` 中，`com.android.build.api.transform.Context` 接口的实现类由原来的 `TransformTask` 变成了匿名内部类，[Booster](https://github.com/didi/booster) 已经对 AGP 3.6.1 做了适配

**Comment by yangzhiqian** [comment]
@stytooldex @ymangu163 两位可以在buildscript中单独添加classpath:com.didiglobal.booster:booster-android-gradle-api:1.5.1 (不需要改其他内容)，后续bytex这边测试稳定后也会尝试升级适配。感谢 @johnsonlee 对最新apt的适配。

**Comment by yangzhiqian** [comment]
@stytooldex  AGP3.6.1兼容有问题。本地测试了一下，是getter-setter内联插件获取keep规则hook proguard出现agp不兼容了，看是因为3.6.1将ProGuardTransform去掉了导致的，如果确实在3.6.x及之上的agp上使用，建议暂时关闭getter-setter内联插件，后面的版本去修复。
@ymangu163 你这个问题暂时没复现，可以尝试使用在buildscrpt中添加classpath "com.didiglobal.booster:booster-android-gradle-api:1.5.1"（其他不用动）试试，有问题再贴一下详细一点的堆栈日志吧。 感谢 @johnsonlee 的agp兼容。

**Comment by yangzhiqian** [comment]
0.1.8已修复 [https://github.com/bytedance/ByteX/pull/47](url)
