### ISSUE TITLE
./gradlew clean assembleRelease 偶现transformClassesWithByteXForRelease失败

### ISSUE THREAD

**Issue by paul1992li** [bytedance/ByteX#29]
AGP版本  3.2.1
Gradle版本 4.9

![image](https://user-images.githubusercontent.com/12912067/81262284-2170d100-9070-11ea-92c0-bd8c968f0526.png)

**Comment by yangzhiqian** [comment]
类重复了，是不是前面还有其他transform？或者一个库多次依赖(maven不能解决高低版本的情况)

**Comment by yangzhiqian** [comment]
> 类重复了，是不是前面还有其他transform？或者一个库多次依赖(maven不能解决高低版本的情况)

你这里是db和okhttp这两个module都包含了com/tencent/qgame/okhttp/BuildConfig这个class。你是不是这两个module的packagename是一样的？

**Comment by paul1992li** [comment]
两个packagename不一样 ，另外这两个moudle之间没有依赖关系，不过这个okhttp会被多次依赖但是主module会implementaion 其他的都只是compileOnly。这个问题是引入Bytex后偶现的，删除主工程build目录可以解决这个问题，不知道什么原因

**Comment by yangzhiqian** [comment]
这边没法复现你这个问题，会不会是你切分支导致的？报错的提示信息中显示有两个同名class进入transform阶段，但并不属于project的输入。目前抖音不管是debug还是release使用bytex编译，除了项目依赖有问题其他的情况没有反馈这类问题。

**Comment by paul1992li** [comment]
继续观察吧
