### ISSUE TITLE
access_inline 问题

### ISSUE THREAD

**Issue by jokermonn** [bytedance/ByteX#30]
新建一个工程，仅引入 access_inline 插件会打出一个空包。另外，在仅引入 ByteX 插件情况下会编译不过

```
apply plugin: 'bytex'
apply plugin: 'bytex.access_inline'

ByteX {
    enable true
    enableInDebug true
    logLevel "DEBUG"
}

// access 内联
access_inline {
    enable true
    enableInDebug true
    logLevel "DEBUG"
}
```

![image](https://user-images.githubusercontent.com/16160722/81281162-0ca23680-908c-11ea-90a2-bf5f06241f6c.png)

**Comment by yangzhiqian** [comment]
能报一下编译环境吗？还有问题能详细一些吗？空包是没有任何代码的意思？

**Comment by jokermonn** [comment]
看了下，access_inline 应该是 AGP 版本过高导致的，但是【仅引入 ByteX 插件情况下会编译不过】的问题在低版本依然存在，AGP 3.5.3 可测

**Comment by yangzhiqian** [comment]
> 看了下，access_inline 应该是 AGP 版本过高导致的，但是【仅引入 ByteX 插件情况下会编译不过】的问题在低版本依然存在，AGP 3.5.3 可测

感谢反馈。access_inline应该和agp版本关系不大，可以再告知一些多的信息，我这边排查。这个我这边复现了，貌似这个是agp的一个bug，我这边断点发现，在没有子插件(进使用)

**Comment by jokermonn** [comment]
新建一个工程，AGP 3.6.3

**Comment by yangzhiqian** [comment]
> 新建一个工程，AGP 3.6.3

好的，这边没测试过3.6.3.但这边3.5.3没遇到相关问题。已知getter-setter在3.6上是有问题的，所以目前bytex算是兼容到了3.5.3.

**Comment by yangzhiqian** [comment]
0.1.8可以试试，测试过AGP3.6没有问题 [https://github.com/bytedance/ByteX/pull/47](url)
