### ISSUE TITLE
access_inline插件报错

### ISSUE THREAD

**Issue by masanpao** [bytedance/ByteX#33]
com.ss.android.ugc.bytex.common.graph.InterfaceNode cannot be cast to com.ss.android.ugc.bytex.common.graph.ClassNode

XXX接口转换错误

kotlin源码
```
class Foo : XXX {
  override fun operateOnIdlePkGame() {
    ui {
      super.operateOnIdlePkGame()
    }
  }
}

interface XXX {
  @JvmDefault
  fun operateOnIdlePkGame() {
    //doNothing
  }
}
```
XXX本来应该按照语法糖的方式编译, 但是看起来被识别为了class...(java8编译方式)

```
    minsdk: 18
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
```

**Comment by BinLia** [comment]
//语法糖方式
[AccessMethod] Access$ method : className = [com/ss/android/ugc/bytex/example/base/Foo], methodName = [access$operateOnIdlePkGame$s70822], desc = [(Lcom/ss/android/ugc/bytex/example/base/Foo;)V] access to public method or field. Target MethodEntity (owner = [com/ss/android/ugc/bytex/example/base/XXX$$CC], name = [operateOnIdlePkGame], desc = [(Lcom/ss/android/ugc/bytex/example/base/XXX;)V])

//异常情况, 被当做java8处理
className = [com/ss/android/ugc/bytex/example/base/Foo], methodName = [access$operateOnIdlePkGame$s70822], desc = [(Lcom/ss/android/ugc/bytex/example/base/Foo;)V] access to public method or field. Target MethodEntity (owner = [com/ss/android/ugc/bytex/example/base/XXX], name = [operateOnIdlePkGame], desc = [()V])

**Comment by yangzhiqian** [comment]
测试用例和报错能贴详细一些吗？还有编译的环境信息。语法糖是没有在脱离d8的情况下走desugar吗？

**Comment by BinLia** [comment]
> 测试用例和报错能贴详细一些吗？还有编译的环境信息。语法糖是没有在脱离d8的情况下走desugar吗？

你是说 
android.enableD8=true
android.enableD8.desugaring=false
android.enableDesugar=true
这个吗

**Comment by BinLia** [comment]
我们项目中没加上述那个

**Comment by masanpao** [comment]
应该是 没有在脱离d8的情况下走desugar  .... 

现在我们项目靠的是d8, 难怪有这个问题.

**Comment by masanpao** [comment]
d8脱糖, 你们这个插件大概什么时候支持java8语法?

**Comment by masanpao** [comment]
private List<MemberEntity> confirmAccess(MemberEntity target) {
        List<MemberEntity> accessShouldBeChangeList = new ArrayList<>();
        Node classNode = graph.get(target.className());
        //修复....
        if(!(classNode instanceof ClassNode)){
            throw new ShouldSkipInlineException("Target class not a ClassNode");
        }
        ....
    }

**Comment by yangzhiqian** [comment]
> d8脱糖, 你们这个插件大概什么时候支持java8语法?
> 
> access_inline这个插件还不支持白名单.... 我们gradle是3.4.2, 默认是走d8脱糖的... 那肯定就会存在上述的问题了....

嗯，目前脱离脱糖有一些插件确实会有点问题，这里确实一个白名单。你下面的修改可以提个pr吧
