### ISSUE TITLE
删行号的plugin没有实现吗？

### ISSUE THREAD

**Issue by Dwan-xie** [bytedance/ByteX#34]

**Comment by yangzhiqian** [comment]
删除行可以用SourceFileKiller,proguard也可以删除，这里只是做个示例代码。你问题的是抖音用的行号优化插件，这个不开源？

**Comment by Dwan-xie** [comment]
SourceFileKiller是已经实现了删除行号吗？看plugin只是写了delete
只是单纯的删除行号，那对于crash后信息的行号是做了提前的处理吗？

**Comment by yangzhiqian** [comment]
> SourceFileKiller是已经实现了删除行号吗？看plugin只是写了delete
> 只是单纯的删除行号，那对于crash后信息的行号是做了提前的处理吗？

bytex中这个SourceFIleKiller只是一个示例代码，可以理解只是删除行号。如果需要可以解析的优化行号，可以参考支付宝的技术博客文章:https://juejin.im/post/5be9485a51882516b937785f .这个方案已经有不少大点的厂实现了(我知道有支付宝、头条系和快手等)，具体实现都没有开源出来，这个估计都考虑到需要各自的crash解析平台，有兴趣可以研究一下。

**Comment by Dwan-xie** [comment]
@yangzhiqian 了解了。
debugitem分区是最关键的，讲这块文章很少，最好还是要自己处理指令行号和真实行号的对应关系。
