### ISSUE TITLE
byteX对于构建速度的优化的疑问

### ISSUE THREAD

**Issue by softrice** [bytedance/ByteX#35]
> 如果所有feature都开发一个单独的插件，每个插件编译构建耗时+10s，各个插件叠在一起，编译耗时就会呈线性增长。

请问字节的产品在使用后ByteX后，有没有编译速度方面提升的数据对比。

**Comment by TellH** [comment]
@softrice 对编译速度的收益要看项目代码量和已有的字节码插件数量。目前抖音项目里基于bytex的插件应该有十多个了，项目也是巨无霸级别了，假如这十几个插件都不基于ByteX实现，各自形成transform，他们串行执行的效率将会非常的低。
基于ByteX实现，能最大程度减少class文件的IO次数，充分利用打包机的多核资源，提升class文件的处理效率。

**Comment by yangzhiqian** [comment]
长时间不回复->close。
