### ISSUE TITLE
aab应用能使用shrink-r-plugin吗？

### ISSUE THREAD

**Issue by beyondckw** [bytedance/ByteX#36]

**Comment by TellH** [comment]
应该是没有问题的，我们一直都在用。
如果有遇到问题，可以随时反馈给我们

**Comment by beyondckw** [comment]
好像是不行，编译不过，我这边是as 4.0

**Comment by beyondckw** [comment]
com.android.build.gradle.internal.pipeline.TransformTask$2$1 cannot be cast to org.gradle.api.internal.AbstractTask
Possible causes for this unexpected error include:
Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
Re-download dependencies and sync project (requires network)

The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.
Stop Gradle build processes (requires restart)

Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.

In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.

**Comment by beyondckw** [comment]
gradle 6.2.1, apg 3.6.2

**Comment by yangzhiqian** [comment]
> com.android.build.gradle.internal.pipeline.TransformTask$2$1 cannot be cast to org.gradle.api.internal.AbstractTask
> Possible causes for this unexpected error include:
> Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
> Re-download dependencies and sync project (requires network)
> 
> The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.
> Stop Gradle build processes (requires restart)
> 
> Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.
> 
> In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.

请将getter-setter、coverage、RFileKnife这三个插件先关闭掉。目前这个三个插件对agp3.6是存在不兼容的，目前agp能兼容到agp3.5.3.你这里提到的shrink-r-plugin目前都是能正常处理的，新版本agp上有问题可以再提问题。

**Comment by yangzhiqian** [comment]
太长时间未回复，close
