### ISSUE TITLE
shrinkResources 兼容 Dynamic Feature 的代码能开源一下吗？有没有ktx的版本

### ISSUE THREAD

**Issue by beyondckw** [bytedance/ByteX#37]

**Comment by yangzhiqian** [comment]
具体是什么功能？ByteX有一个ShrinkR,是处理字节码的，你说的是shrinResource资源处理？

**Comment by beyondckw** [comment]
shrinResource资源处理

**Comment by woshitangebupasui** [comment]
shrinkResources 兼容 Dynamic Feature的插件目前还没有开源版本，这部分有关包大小的插件开源计划目前还在讨论中。可以持续关注下我们的技术公众号，后续开源之后我也会在这个issue中同步的。

**Comment by woshitangebupasui** [comment]
> shrinResource资源处理

shrinkResources 兼容 Dynamic Feature的插件目前还没有开源版本，这部分有关包大小的插件开源计划目前还在讨论中。可以持续关注下我们的技术公众号，后续开源之后我也会在这个issue中同步的。
