### ISSUE TITLE
shrinkR会将build中动态生成的java类给删除了

### ISSUE THREAD

**Issue by haryzhang4256** [bytedance/ByteX#39]
请问这个里面有对java 或者 非R 的class做处理吗？ 
我的项目关闭shrinkR就没问题，打开shrinkR就将该类优化没了。

**Comment by yangzhiqian** [comment]
应该和shrinkR关系不大吧，shrinkR严格匹配了R的类名，有测试用例吗？目前抖音这边没有相关的反馈。

**Comment by yangzhiqian** [comment]
长时间未反馈，close，有问题再open
