### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException (no error message)

### ISSUE THREAD

**Issue by jem-cordern** [bytedance/ByteX#40]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':shell_app:transformClassesWithByteXForIcityRelease'.
> java.lang.ArrayIndexOutOfBoundsException (no error message)

这个问题是插件本身的，还是我这边集成出了问题，麻烦看一下吧

**Comment by yangzhiqian** [comment]
--stacktrace一下看一具体的报错堆栈。

**Comment by yangzhiqian** [comment]
> --stacktrace一下看一具体的报错堆栈。

这个问题抖音有遇到过类似的，是某些库(抖音遇到的是com/hianalytics/android/这个包(华为的)的库)的字节码使用asm读取就会挂，还没到插件处理阶段。这个有处理方案，一个是提前desugar，或者bytex加白名单忽略(不建议)

**Comment by yangzhiqian** [comment]
长时间未回复，close
