### ISSUE TITLE
编译时报错，无法找到这个jar

### ISSUE THREAD

**Issue by ziyouxiaozi** [bytedance/ByteX#48]
Could not find com.bytedance.android.byteX:ProguardConfigurationResolver:0.1.8.
Searched in the following locations:
  - file:/F:/Android demo/ByteX-master/gradle_plugins/com/bytedance/android/byteX/ProguardConfigurationResolver/0.1.8/ProguardConfigurationResolver-0.1.8.pom
  - file:/F:/Android demo/ByteX-master/gradle_plugins/com/bytedance/android/byteX/ProguardConfigurationResolver/0.1.8/ProguardConfigurationResolver-0.1.8.jar
  - https://dl.google.com/dl/android/maven2/com/bytedance/android/byteX/ProguardConfigurationResolver/0.1.8/ProguardConfigurationResolver-0.1.8.pom
  - https://dl.google.com/dl/android/maven2/com/bytedance/android/byteX/ProguardConfigurationResolver/0.1.8/ProguardConfigurationResolver-0.1.8.jar
  - https://jcenter.bintray.com/com/bytedance/android/byteX/ProguardConfigurationResolver/0.1.8/ProguardConfigurationResolver-0.1.8.pom
  - https://jcenter.bintray.com/com/bytedance/android/byteX/ProguardConfigurationResolver/0.1.8/ProguardConfigurationResolver-0.1.8.jar
Required by:
    project :example > com.bytedance.android.byteX:getter-setter-inline-plugin:0.1.8 > com.bytedance.android.byteX:HookProguard:0.1.8

**Comment by TellH** [comment]
Hi @ziyouxiaozi, please try again. Those components are added to jcenter.
