### ISSUE TITLE
接入后编译没有反应

### ISSUE THREAD

**Issue by RinOrz** [bytedance/ByteX#49]
接入 byteX 任意一个插件后编译时没有看到有关 transform 的 task 输出，且 android 项目编译完成后 apk 中丢失了所有的 dex 文件！！！

**环境:**
> Android Gradle 4.2.0-alpha07
> Android Studio 4.2 Canary 7
> Kotlin Gradle DSL
> Kotlin Compiler 1.4

build.gradle.kts -> 
![image](https://user-images.githubusercontent.com/58068445/90036641-db25b080-dcf5-11ea-97d3-3f3af469b211.png)
![image](https://user-images.githubusercontent.com/58068445/90036683-e678dc00-dcf5-11ea-9915-3219cfe68d77.png)
![image](https://user-images.githubusercontent.com/58068445/90036705-eaa4f980-dcf5-11ea-8adc-301441f30800.png)

**Comment by yangzhiqian** [comment]
这个能看到这个task有执行吗？transform目录下有输出吗？

**Comment by oh-Rin** [comment]
> 这个能看到这个task有执行吗？transform目录下有输出吗？

task貌似没有执行，目录下没有任何文件

**Comment by TellH** [comment]
> > 这个能看到这个task有执行吗？transform目录下有输出吗？
> 
> transform-task貌似没有执行，目录下没有任何文件

能截图看看app下的build目录的内容吗

**Comment by yangzhiqian** [comment]
0.2.4已经修复了apk为空的问题，可以再试试呢？这个源于一个在3.6.0及以上的兼容性bug，在只有bytex这个transform时触发。

**Comment by yangzhiqian** [comment]
长时间未反馈，close，有问题再open
