### ISSUE TITLE
SourceFileKill 这个插件的原理是什么呢？

### ISSUE THREAD

**Issue by JuneLeo** [bytedance/ByteX#51]
其实我对这个SourceFileKill的原理
我自己的理解是这个插件的作用是将 class 字节码中的  SourceFile和LineNumberTable 去除掉，但是查看插件中的源码和编译example ，生成的transform/Bytex 中的class中，我发现SourceFile和LineNumberTable 都是存在的，并没有删除，期待收到您的答复！

**Comment by yangzhiqian** [comment]
我这边看到的ByteX输出看已经将SourceFile与LineNumberTable都去掉了啊，原理是不调用super方法，这样后面的ClassVisitor(其实是对应了ClassWriter)就不会输出到最后的class中了，完成了这两个属性的删除.
这个插件是ByteX提供的示例插件代码，因为这个插件最简单。SourceFile和LineNumberTable实际上是可以删除的，这样直接删除会造成后面查看crash日志有困难
