### ISSUE TITLE
app bundle dynamicFeatures 构建失败？

### ISSUE THREAD

**Issue by xiandongluo** [bytedance/ByteX#53]
我们有几个dynamicFeatures，这个导致打包失败
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':xxx:transformDexWithDexSplitterForArmRelease'.
> com.android.build.api.transform.TransformException: com.android.tools.r8.utils.FeatureClassMapping$FeatureMappingException: Invalid mappings specification: Redefinition of predicate XX.XXX.XXX.XXX.XXX.BuildConfig not allowed
   in file null:0

**Comment by yangzhiqian** [comment]
支持

**Comment by yangzhiqian** [comment]
AGP aab打包的bug

**Comment by JayFang1993** [comment]
@yangzhiqian 为何认定这个是agp的bug？
