### ISSUE TITLE
method-call-opt-plugin 行号问题

### ISSUE THREAD

**Issue by geekTaolipeng** [bytedance/ByteX#56]
问题：在已知使用 method-call-opt-plugin 插件情况下，线上某个bug导致崩溃，崩溃行数上报信息无法一一对应。
simple 
```java
public void test(boolean con) {
        Log.d(con ? "con" : "no con", "con");     // Line number 33
        Log.d("log", "log");                                 // Line number 34
        Log.d(TAG, "log");                                // Line number 35
        Log.d("log", String.valueOf(1));          // Line number 36
        Log.d("log", "log" + 1 + "c" + 2 + "d" + toString());         // Line number 37
        Log.d("log", getClass().getSimpleName());                    // Line number 38
        Log.d("log", this.toString());                                           // Line number 39
        getLong();                                                                     // Line number 40
        int a = 0;                                                                       // Line number 41
        int b = 4 / a;                                                               // Line number 42
        Log.d("log", b + "");                                                  // Line number 43
    }
```
报错：
 ` Caused by: java.lang.ArithmeticException: divide by zero
        at com.ss.android.ugc.bytex.example.log.LogTest.test(Unknown Source:15)
        at com.ss.android.ugc.bytex.example.MainActivity.onCreate(Unknown Source:20)`

实际应该是  42行

**Comment by yangzhiqian** [comment]
我zhe这边测试了一下，发现bytex处理之后的字节码报错的地方行号没有问题(前面一些优化遗留了部分行号信息，但我理解不影响你这次报错的问题)，这个你能将你的测试编译中间产物发一下吗？在app/build/intermediates/transforms/ByteX/$variant/下面有很多class或者jar的产物，里面找出对应的class？
![image](https://user-images.githubusercontent.com/17828748/92080714-8ce76700-edf4-11ea-9f51-99d122c15745.png)

**Comment by yangzhiqian** [comment]
我这边测试优化之后的class反编译看是下面的，上图中框柱的地方有行号76的标记，所以我理解除报错虚拟机会告诉是76行报错的
![image](https://user-images.githubusercontent.com/17828748/92080942-e64f9600-edf4-11ea-8b21-3fa8c8649b2a.png)

**Comment by geekTaolipeng** [comment]
你好,我是今天clone 这个项目进行测试。
用android studio 打的 release 包
 具体改了几项：
   
![bytex](https://user-images.githubusercontent.com/43661320/92083911-421c1e00-edf9-11ea-9576-69057fbb3cbc.png)
![byte2](https://user-images.githubusercontent.com/43661320/92083958-52cc9400-edf9-11ea-89c5-9634c459d3a2.png)

**android studio  版本号**
   Android Studio 4.0.1
   Build #AI-193.6911.18.40.6626763, built on June 25, 2020
   Runtime version: 1.8.0_242-release-1644-b3-6222593 x86_64
   VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
   macOS 10.15.6
   GC: ParNew, ConcurrentMarkSweep
  Memory: 1237M
  Cores: 8
  Registry: ide.new.welcome.screen.force=true
  Non-Bundled Plugins: ASM Bytecode Outline, ASM Bytecode Viewer, org.jetbrains.kotlin, cn.yiiguxing.plugin.translate, 
  jclasslib


**app/build/intermediates/transforms/ByteX/$variant/ 打包的产物**
[LogTest.class.zip](https://github.com/bytedance/ByteX/files/5166882/LogTest.class.zip)

**Comment by geekTaolipeng** [comment]
@yangzhiqian 
  我取消了其他插件使用，只留下 apply plugin: 'bytex.method_call_opt'  
  能够匹配正确的行号
