### ISSUE TITLE
升级kotlin到1.4.10后报错

### ISSUE THREAD

**Issue by xuduo** [bytedance/ByteX#61]
android gradle plugin:4.0.2
gradle version: 6.6.1
kotlin plugin version: 1.4.10 （使用1.3.72正常）
byteX verson:0.2.2

18:22:15 * What went wrong:
18:22:15 Execution failed for task ':main:transformClassesWithByteXForGooglePlayBillAbi32Release'.
18:22:15 > java.lang.RuntimeException: java.lang.RuntimeException: Failed to resolve class META-INF/versions/9/module-info.class[
18:22:15   transform input:
18:22:15   	/data/uhome/builder/.gradle/caches/transforms-2/files-2.1/5b3f057d4931086bccb73195ccad7e5b/jetified-kotlin-stdlib-jdk7-1.4.10.jar!META-INF/versions/9/module-info.class
18:22:15   	/data/uhome/builder/.gradle/caches/transforms-2/files-2.1/8613476db420f8b57e3847f668780a73/jetified-kotlin-stdlib-1.4.10.jar!META-INF/versions/9/module-info.class
18:22:15   project input:
18:22:15   	/data/uhome/builder/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk7/1.4.10/30e46450b0bb3dbf43898d2f461be4a942784780/kotlin-stdlib-jdk7-1.4.10.jar!META-INF/versions/9/module-info.class
18:22:15   	/data/uhome/builder/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.4.10/ea29e063d2bbe695be13e9d044dcfb0c7add398e/kotlin-stdlib-1.4.10.jar!META-INF/versions/9/module-info.class
18:22:15   aar input:not found]

**Comment by yangzhiqian** [comment]
java9的指令，升级到bytex 0.2.3即可

**Comment by xuduo** [comment]
> java9的指令，升级到bytex 0.2.3即可
升级之后依然报同样的错误

**Comment by yangzhiqian** [comment]
/data/uhome/builder/.gradle/caches/transforms-2/files-2.1/5b3f057d4931086bccb73195ccad7e5b/jetified-kotlin-stdlib-jdk7-1.4.10.jar!META-INF/versions/9/module-info.class
18:22:15 /data/uhome/builder/.gradle/caches/transforms-2/files-2.1/8613476db420f8b57e3847f668780a73/jetified-kotlin-stdlib-1.4.10.jar!META-INF/versions/9/module-info.class
这里貌似有两个相同的class，这个符合你们预期吗

**Comment by yangzhiqian** [comment]
jetified-kotlin-stdlib-jdk7-1.4.10.jar      /jetified-kotlin-stdlib-1.4.10.jar

**Comment by yangzhiqian** [comment]
如果你需要忽略重复类型检查，可以在gradle.properties中添加bytex.enableDuplicateClassCheck=false来关闭类重复检查，但我们不建议这么做。0.2.3更新了ASM6，可以解析java9的module.class,但打入到apk中的class有两个module.class，这个会被类重复检查给block住。原因就在这里。
