### ISSUE TITLE
java.lang.IllegalStateException: The configuration :app:originDebugRuntimeClasspath was resolved from a thread not managed by Gradle

### ISSUE THREAD

**Issue by yanchunlan** [bytedance/ByteX#63]
as 3.4.2，gradle 6.1.1

配置信息：
ext .bytex_version = '0.2.3'
classpath "com.bytedance.android.byteX:base-plugin:${bytex_version}"
classpath "com.bytedance.android.byteX:shrink-r-plugin:${bytex_version}"

def pluginEnable = true
def pluginEnableInDebug = true
def pluginLogLevel = "DEBUG"
apply plugin: 'bytex'
ByteX {
    enable pluginEnable
    enableInDebug pluginEnableInDebug
    shouldSaveCache false
    logLevel pluginLogLevel
}
apply plugin: 'bytex.shrink_r_class'
shrinkR {
    enable pluginEnable
    enableInDebug pluginEnableInDebug
    logLevel pluginLogLevel
    keepList = [
            "android.support.constraint.R.id",
    ]
}

编译报错如下：

> Task :app:transformClassesWithByteXForOriginDebug
beforeExecute transformClassesWithByteXForOriginDebug
Process init cost time = [11 ms]
Process loading cache cost time = [8 ms]
Total cost time = [4926 ms]
afterExecute transformClassesWithByteXForOriginDebug true org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:transformClassesWithByteXForOriginDebug'.

> Task :app:transformClassesWithByteXForOriginDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithByteXForOriginDebug'.
> java.lang.IllegalStateException: java.lang.IllegalStateException: The configuration :app:originDebugRuntimeClasspath was resolved from a thread not managed by Gradle.

**Comment by yangzhiqian** [comment]
--S一下看一下堆栈？必现吗

**Comment by yanchunlan** [comment]
必现
![Uploading 521c22be8ec434e371bed47235354257.png…]()

**Comment by yanchunlan** [comment]
![521c22be8ec434e371bed47235354257](https://user-images.githubusercontent.com/19542278/96432569-8f344200-1237-11eb-9105-efe97d484043.png)

必现

**Comment by yanchunlan** [comment]
此问题后面降低gradle 版本到 3.4.1就可以了

**Comment by yangzhiqian** [comment]
升级到0.2.4并且在gradle.properties中加入bytex.forbidUseLenientMutationDuringGetArtifact=true 可以修复这个问题

**Comment by githubzaibao** [comment]
升级到0.2.5 也使用了gradle.properties中加入bytex.forbidUseLenientMutationDuringGetArtifact=true，该问题还是没有解决
