### ISSUE TITLE
java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: Failed to resolve class META-INF/versions/9/module-info.class

### ISSUE THREAD

**Issue by yanchunlan** [bytedance/ByteX#64]
kotlin  版本改到1.4.0，就报错如下：

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':example:transformClassesWithByteXForBytexCnDebug'.
> java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: Failed to resolve class META-INF/versions/9/module-info.class[
  transform input:
  	/Users/yanchunlan/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk7/1.4.0/9cc187c3dfaf6e4001bdf962e3cdadff7690261b/kotlin-stdlib-jdk7-1.4.0.jar!META-INF/versions/9/module-info.class
  	/Users/yanchunlan/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.4.0/63e75298e93d4ae0b299bb869cf0c627196f8843/kotlin-stdlib-1.4.0.jar!META-INF/versions/9/module-info.class
  project input:
  	/Users/yanchunlan/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk7/1.4.0/9cc187c3dfaf6e4001bdf962e3cdadff7690261b/kotlin-stdlib-jdk7-1.4.0.jar!META-INF/versions/9/module-info.class
  	/Users/yanchunlan/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.4.0/63e75298e93d4ae0b299bb869cf0c627196f8843/kotlin-stdlib-1.4.0.jar!META-INF/versions/9/module-info.class
  aar input:not found]

**Comment by yangzhiqian** [comment]
module-info.class有两个，todo：类重复检查兼容

**Comment by yangzhiqian** [comment]
升级到0.2.4可以修复这个问题
