### ISSUE TITLE
Double-Checked Locking

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [bytedance/ByteX#67]
https://github.com/bytedance/ByteX/blob/be4ad73da1a991482575780e25273287ccd6df69/TransformEngine/src/main/java/com/ss/android/ugc/bytex/transformer/cache/FileData.java#L41-L43

Double-Checked Locking is widely cited and used as an efficient method for implementing lazy initialization in a multithreaded environment.
Unfortunately, it will not work reliably in a platform independent way when implemented in Java, without additional synchronization.

**Comment by yangzhiqian** [comment]
useless
