### ISSUE TITLE
Unused Field

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [bytedance/ByteX#68]
https://github.com/bytedance/ByteX/blob/be4ad73da1a991482575780e25273287ccd6df69/common/src/main/java/com/ss/android/ugc/bytex/common/utils/CalendarUtils.java#L14
https://github.com/bytedance/ByteX/blob/be4ad73da1a991482575780e25273287ccd6df69/common/src/main/java/com/ss/android/ugc/bytex/common/utils/CalendarUtils.java#L19

These fields are never used.

**Comment by yangzhiqian** [comment]
useless
