### ISSUE TITLE
transformClassesWithShrinkRFileForRelease失败

### ISSUE THREAD

**Issue by ksforme** [bytedance/ByteX#71]
java.lang.RuntimeException: There are some unused resource, please review those resource and try to delete them, you can check it out in file shrinkR/unused_res.json. 
   在你的commit上发现了一些无用的资源，辛苦你review一下这些资源，如果发现确实没有引用，可以尝试删掉，再rebuild。如果有问题请@谭乐华。
  
这个有白名单可以keep吗

**Comment by yangzhiqian** [comment]
无用资源检查到你的项目中可能存在无用的资源，是做包大小监控的，shrinkR/unused_res.json.中列出的资源没有使用到可以删除再编译/或者加白名单.

**Comment by ksforme** [comment]
已解决

**Comment by GaoGates** [comment]
> 已解决

您好，遇到同样问题，请问怎么解决的

**Comment by yangzhiqian** [comment]
确认无用资源是否真的没有用到，如果没有用到建议移除来减小包大小，如果有用到或者不好删，可以加白名单，详细看shrinkR的readme。
