### ISSUE TITLE
不支持AGP4.1.0

### ISSUE THREAD

**Issue by kinkenrin** [bytedance/ByteX#72]
AGP4.1.0
一打包就出现如下报错，无法打包
Execution failed for task ':app:transformClassesWithByteXForDebug'.
> java.lang.NoSuchMethodError (no error message)

配置如下：
ext.plugin_version="0.2.5"

// apply ByteX宿主
apply plugin: 'bytex'
ByteX {
    enable true
    enableInDebug true
    logLevel "DEBUG"
}

apply plugin: 'bytex.shrink_r_class'
shrinkR {
    enable true
    enableInDebug true
    logLevel "DEBUG"
    keepList = [
            // keep android.support.constraint.R里所有id
            "android.support.constraint.R.id",
            // keep 所有以im_e为前缀的drawable字段
            "R.drawable.im_e+",
    ]
    resCheck {
        enable true // 无用资源检查的开关
        // 根据资源所在的路径做模糊匹配（因为第三方库用到的冗余资源没法手动删）
        onlyCheck = [
                // 只检查主工程里的资源
                "app/build"
        ]
        // 检查白名单。这些资源就算是冗余资源也不会report出来
        keepRes = [
                "R.drawable.ic_list_dou_order",
                "R.string.snapchat_tiktok_client_id",
                "R.string.snapchat_musically_client_id",
                "R.string.fb_account_kit_client_token",
                "R.string.mapbox_*",
                "R.string.kakao*",
                "R.dimen",
                "R.color",
                "R.animator",
                "R.integer",
                "R.bool",
                "R.style",
                "R.styleable",
                "R.attr",
                "R.xml",
                "R.array",
                "R.string"
        ]
    }

    assetsCheck {
        enable true // 冗余assets资源检查开关
        keepBySuffix = [
                ".model",
                ".otf",
                ".ttf"
        ]
        keepAssets = [
                "start_anim/",
                "Contour_2D/",
        ]
    }
}

**Comment by yangzhiqian** [comment]
完整的报错堆栈发一下呢？这个日志看不出什么问题，也许是agp不兼容的问题。

**Comment by yangzhiqian** [comment]
试试0.2.7呢，AGP相关的兼容做了一些。

**Comment by yangzhiqian** [comment]
新版本已经修复，长时间无反馈，close
