### ISSUE TITLE
想问下目前支持AGP3.6版本和R8吗

### ISSUE THREAD

**Issue by hyperion-mk2** [bytedance/ByteX#77]
AGP3.6和3.6以下编译流程发生了变化，有考虑兼容吗？

**Comment by yangzhiqian** [comment]
ByteX框架对AGP的依赖度比较低，用的是标准的transform那一套，兼容性测试没发现有什么问题。主要有些插件可能依赖某些AGP的接口(比如getter-setter依赖proguard),你那边是有什么问题吗？可以将遇到的问题贴出来，我们这边也逐步去解决。目前内部最适配的环境是AGP3.5.3&gradle5.6.4

**Comment by yangzhiqian** [comment]
新版本已经修复，长时间无反馈，close
