### ISSUE TITLE
居然原封不动的 copy 了 booster 的代码？

### ISSUE THREAD

**Issue by johnsonlee** [bytedance/ByteX#8]

**Comment by Omooo** [comment]
Mark～

**Comment by yangzhiqian** [comment]
感谢反馈。你是指使用了booster的对gradle api的封装那块代码吧？在booster开源之前ByteX已经在公司内多个app上稳定运行了半年，这块代码是在booster开源之后引入到了bytex中，更多的作为工具类使用，这一块封装确实挺好用，所以我们原始地将实现参照了过来，我们已经在readme上加上鸣谢。

**Comment by walorwang** [comment]
Mark～

**Comment by EvilsoulM** [comment]
已经和booster作者做了沟通，主要是用了booster 做各个版本gradle 兼容的那块逻辑～已经加了booster到主页，后续会直接改成直接引入库的形式～

**Comment by yangzhiqian** [comment]
> 感谢反馈。你是指使用了booster的对gradle api的封装那块代码吧？在booster开源之前ByteX已经在公司内多个app上稳定运行了半年，这块代码是在booster开源之后引入到了ByteX中，更多的作为工具类使用，这一块封装确实挺好用，所以我们直接将那一块代码实现加入到了ByteX，同时我们在readme上表达了对booster贡献的感谢。

https://github.com/bytedance/ByteX/pull/9 已经提了mr，maven依赖了booster对gradle的封装。
