### ISSUE TITLE
Android 接入TPNS 执行checkTPNS过慢的问题

### ISSUE THREAD

**Issue by LeviathanF** [bytedance/ByteX#85]
Android 集成TPNS 之后。
打包Executing task 'checkTPNS' 每次时间长达35分钟，请问这个有地方能关闭吗？
TPNS正常可用

**Comment by LeviathanF** [comment]
<==========---> 82% EXECUTING [5m 39s]
> :app:checkTPNS > Resolve dependencies of :app:implementationCopy2 > maven-metadata.xml

**Comment by yangzhiqian** [comment]
TPNS是什么任务?如果卡住用[jstack](https://www.cnblogs.com/myseries/p/12050083.html)看一下堆栈，判断一下卡住的地方代码是不是有问题。如果是执行慢，可以用jvisualvm分析一下内存看一下是不是有瓶颈,有可能是cpu被gc占用太多。当然也可能是task本身代码有问题.

**Comment by ysj0816** [comment]
我的Android studio 之前编译也很快，接入TPNS后也是 执行编译 :checkTPNS 过慢，每次都在十几分钟左右，请问有什么解决方法吗
