### ISSUE TITLE
请教: 同时支持CoreAPI 和 TreeApi 是否会增加时长?

### ISSUE THREAD

**Issue by yizems** [bytedance/ByteX#87]
![image](https://user-images.githubusercontent.com/16949474/108462601-d733a600-72b7-11eb-9172-140457ab1074.png)

如题, 按理来说 treeAPI 比 coreApi 耗时长;

如果没有影响的话,能简单介绍下怎么实现的么, 非常感谢!

**Comment by yangzhiqian** [comment]
首先说一下，coreAPI和TreeApi应该是二选一的，如果你在coreAPI插了一个桩方法调用，同时在TreeApi中插了一个桩方法调用，那最终的结果是插了两次桩。

**Comment by yizems** [comment]
@yangzhiqian 我的疑问点主要集中在这个方法
![image](https://user-images.githubusercontent.com/16949474/108464717-ace3e780-72bb-11eb-8abf-78474067ebfd.png)

如果我没有使用 这个方法, 而是使用的 core api ,那么这里会不会也会执行, 都会生成对应的ClassNode, 这个过程应该挺耗时的吧

**Comment by yangzhiqian** [comment]
几乎不耗时,忽略影响.

**Comment by yizems** [comment]
好的,谢谢

**Comment by TellH** [comment]
> @yangzhiqian 我的疑问点主要集中在这个方法
> ![image](https://user-images.githubusercontent.com/16949474/108464717-ace3e780-72bb-11eb-8abf-78474067ebfd.png)
> 
> 如果我没有使用 这个方法, 而是使用的 core api ,那么这里会不会也会执行, 都会生成对应的ClassNode, 这个过程应该挺耗时的吧



从极致性能的角度，生成ClassNode确实会增加一点开销，但之前测试过，在可接受的范围内。
