### ISSUE TITLE
methodnode添加局部变量抛出异常

### ISSUE THREAD

**Issue by haizhiyun** [bytedance/ByteX#90]
使用methodNode 给方法添加一个局部变量，common 中发现这里会抛出异常，请问，为什么要这么判断，添加局部变量怎么添加 
    谢谢！
public class CheckedInsnList extends InsnList {

    @Override
    public void add(AbstractInsnNode insn) {
        if (insn.getNext() != null || insn.getPrevious() != null) {
            throw new IllegalStateException();
        }
        super.add(insn);
    }
....
}

**Comment by yangzhiqian** [comment]
抛什么异常？

**Comment by haizhiyun** [comment]
> 抛什么异常？

后面试了下，#1 里面抛出异常那里已经好了，不过插入局部变量还是没成功，不知道你们有这方面的demo没有，可能是我写的不对

**Comment by yangzhiqian** [comment]
可以参考一下AdviceAdapter.newLocal
